const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');

async function generatePrescriptionPDF(prescription, patient, doctor) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // Letter size
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const { width, height } = page.getSize();
  const margin = 50;
  let y = height - margin;

  const darkText = rgb(0.1, 0.1, 0.15);
  const grayText = rgb(0.4, 0.4, 0.45);
  const accentColor = rgb(0.08, 0.6, 0.65);

  // Header
  page.drawText('RoundsAI', {
    x: margin, y, size: 22, font: boldFont, color: accentColor
  });
  y -= 18;
  page.drawText('Digital Prescription', {
    x: margin, y, size: 11, font, color: grayText
  });
  y -= 6;
  page.drawLine({
    start: { x: margin, y: y - 8 },
    end: { x: width - margin, y: y - 8 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.87)
  });
  y -= 34;

  // Doctor + Date
  page.drawText(`Prescribed by: ${doctor?.name || 'Dr. Attending Physician'}`, {
    x: margin, y, size: 11, font: boldFont, color: darkText
  });
  y -= 16;
  const dateStr = new Date(prescription.createdAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });
  page.drawText(`Date: ${dateStr}`, {
    x: margin, y, size: 10, font, color: grayText
  });
  y -= 30;

  // Patient info
  page.drawText('Patient Information', {
    x: margin, y, size: 12, font: boldFont, color: darkText
  });
  y -= 18;
  const age = Math.floor((Date.now() - new Date(patient.dob).getTime()) / (1000 * 60 * 60 * 24 * 365.25));
  page.drawText(`Name: ${patient.name}   |   Age: ${age}   |   Gender: ${patient.gender}`, {
    x: margin, y, size: 10, font, color: darkText
  });
  y -= 14;

  if (patient.allergies && patient.allergies.length > 0) {
    page.drawText(`Known Allergies: ${patient.allergies.join(', ')}`, {
      x: margin, y, size: 10, font, color: rgb(0.7, 0.2, 0.2)
    });
    y -= 14;
  }

  y -= 20;
  page.drawLine({
    start: { x: margin, y: y + 10 },
    end: { x: width - margin, y: y + 10 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.87)
  });
  y -= 10;

  // Medications
  page.drawText('Medications', {
    x: margin, y, size: 12, font: boldFont, color: darkText
  });
  y -= 24;

  prescription.medications.forEach((med, index) => {
    if (y < 100) {
      page.addPage([612, 792]);
      y = height - margin;
    }

    page.drawText(`${index + 1}. ${med.name} — ${med.dosage}`, {
      x: margin, y, size: 11, font: boldFont, color: darkText
    });
    y -= 15;

    const detailParts = [];
    if (med.frequency) detailParts.push(`Frequency: ${med.frequency}`);
    if (med.duration) detailParts.push(`Duration: ${med.duration}`);
    if (detailParts.length > 0) {
      page.drawText(detailParts.join('   |   '), {
        x: margin + 15, y, size: 9.5, font, color: grayText
      });
      y -= 14;
    }

    if (med.notes) {
      page.drawText(`Note: ${med.notes}`, {
        x: margin + 15, y, size: 9.5, font, color: grayText
      });
      y -= 14;
    }

    y -= 12;
  });

  // Footer
  page.drawLine({
    start: { x: margin, y: 70 },
    end: { x: width - margin, y: 70 },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.87)
  });
  page.drawText('Generated by RoundsAI — AI-powered doctor workflow platform', {
    x: margin, y: 55, size: 8, font, color: grayText
  });
  page.drawText('Built with Claude as part of the AB Talks 60-Day Claude AI Challenge.', {
    x: margin, y: 42, size: 8, font, color: grayText
  });

  return await pdfDoc.save();
}

module.exports = generatePrescriptionPDF;